version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpasswordroot
      MYSQL_DATABASE: stocker
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysqlsecretpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: